### ISSUE TITLE
Multiple call of textFieldShouldBeginEditing

### ISSUE THREAD

**Issue by Serg-Pogrebnyak** [heap/heap-ios-autocapture-sdk#1] opened 2023-03-23 15:51 UTC
After install heap ios autocapture textFieldShouldBeginEditing function calling twice. Could you please fix this?

**Comment by bnickel** [comment] 2023-03-24 16:43
Hi Serg,

I've been able to reproduce this behavior.  I see it happening when a `UITextField` or `UITextView` is already active and I tap on a new text field.

When a user interacts with a `UITextField`, we monitor for the end of editing to fire a "Field Edit" event.  Some code that watches for the end of editing checks if the next view that's being touched will become the first responder.  We call `touchedView.canBecomeFirstResponder`, which for text fields calls `textFieldShouldBeginEditing`.

Essentially, the behavior you're seeing is because `canBecomeFirstResponder` is called twice.  We will evaluate if there's a better alternative to avoid this call.

To help us understand the problem, can you add some context about the work you're doing inside `textFieldShouldBeginEditing`? I expected `canBecomeFirstResponder` to be fairly safe to call, but it looks like I was wrong.

**Comment by Serg-Pogrebnyak** [comment] 2023-03-24 16:46
I detect when user tap on the text field and show pop over for select some stuff, and return false to avoid editing

**Comment by bnickel** [comment] 2023-03-24 17:01
Thanks, we'll look for other solutions.  Since our code also only fires when the user taps on the text field, a potential workaround would be to detect if the popup is already being presented before showing.

**Comment by Serg-Pogrebnyak** [comment] 2023-03-24 18:29
I handle this in another way, but calling delegate twice is not good) That's why I created the issue

**Comment by bnickel** [comment] 2023-07-25 20:37
This was fixed in 0.2.0.

The SDK now avoids calling `canBecomeFirstResponder` and exclusively depends on `UITextField.textDidEndEditingNotification` to emit change events.

**Closed as completed by bnickel** 2023-07-25 20:37 UTC
